language: rust
cache: cargo
rust:
- nightly-2019-03-16
script:
- make setup extern build dist
deploy:
  provider: releases
  file: dist/release.zip
  api_key: $GITHUB_ACCESS_TOKEN
  skip_cleanup: true
  on:
    tags: true
